### ISSUE TITLE
Petoi Bittle hangging on Initialize MPU

### ISSUE THREAD

**Issue by leonardolisboa** [PetoiCamp/OpenCatEsp32#2]
Hi, using the standard code, following the changes requested in the manual (Arduino 1.8.19 and all requested changes in code), after compiling and uploading the code to the board, Bittle hangs on "Initialize MPU".
Could you please confirm if I may be missing something?

ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13864
load:0x40080400,len:3608
entry 0x400805f0
Flush the serial buffer...

* Start *
Bittle
Scanning I2C network...
- I2C device found at address 0x54  !
- I2C device found at address 0x68  !
- done
Initializing MPU...

If I replace the mpu6050 folder in src folder of the code by the recommended here: https://docs.petoi.com/biboard/demo-applications/6.gyro-imu-mpu6050 then the below error message is shown when compiling the code in Arduino.

'class MPU6050' has no member named 'dmpGetCurrentFIFOPacket'

Uploading the code using the Desktop tool works fine and Bittle works.

Thanks,
Leonardo

**Comment by JasonWong08** [comment]
The code in https://docs.petoi.com/biboard/demo-applications/6.gyro-imu-mpu6050 shou
We have made some optimizations on the basis of the library in https://docs.petoi.com/biboard/demo-applications/6.gyro-imu-mpu6050 and added the function dmpGetCurrentFIFOPacket(). Thank you for your reminder, we have updated the library file on this website.
