### ISSUE TITLE
Missing File -> Compile Error

### ISSUE THREAD

**Issue by wrightleft** [PetoiCamp/OpenCatEsp32#23]
As I commented here -> https://github.com/PetoiCamp/OpenCatEsp32/commit/20ee5aeae00e9056f53e4fd533d7b964a2339ef9#r145497366

The pull request was merged to master without the missing file causing a compile error.
```
OpenCatEsp32\src\moduleManager.h:49:10: fatal error: backTouch.h: No such file or directory
```

**Comment by borntoleave** [comment]
Thanks for reporting. Fixed.
