### ISSUE TITLE
Missing ifdef -> Compile Error

### ISSUE THREAD

**Issue by wrightleft** [PetoiCamp/OpenCatEsp32#24]
As I commented here -> https://github.com/PetoiCamp/OpenCatEsp32/commit/adbd441df8c379e54b25740e79b76d90097f0c0b#r145497406

The missing ifdef causes a compile error when `ULTRASONIC` is not defined.
```
OpenCatEsp32\src\reaction.h:692:35: error: 'readUltrasonic' was not declared in this scope
```

**Comment by borntoleave** [comment]
Thanks for reporting. Fixed.
